version: '3.8'
services:
  obs-build-env:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      # Enable OBS build on container start
        ENABLE_BUILD: "ON"  

      # If ON, the default Build options will be sent to CMake
      # Defaults: "-DCEF_ROOT_DIR=\"/home/cef\"

      # -DENABLE_PIPEWIRE=OFF -DENABLE_AJA=0 -DENABLE_WEBRTC=0 
      #-DQT_VERSION=6"
      # In all cases, CEF_ROOT_DIR must be set to /home/cef

#        CMAKE_DEFAULTS: "ON"

      # Custom CMake options, if you want to override the default ones
      # Remove the comment and specify the options you want to use
      # Please note that the default options will be ignored if this is set      
      
      #  CMAKE_OPTIONS: "-DQT_VERSION=6 -DENABLE_WEBRTC=0"  # Custom CMake options

# If you wush to persist the OBS Builds dir, uncomment the following lines
#   and create a folder named "obs-builds" in the root of your local workspace

#    volumes:
#      - ./obs-builds:/commandhistory


    command: sleep infinity

#volumes:
#      - type: bind
#        source: ${localWorkspaceFolder}/home/obs-studio
#        target: /workspace
#        consistency: cached
